apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  RABBITMQ_HOST: "rabbitmq"
  ASPNETCORE_URLS: "http://+:8083"
  ASPNETCORE_ENVIRONMENT: "Production"
  PAYMENT_QUEUE: "catalog-payment-queue"
  MONGODB_CONNECTION_STRING: mongodb://mongodb:27017
  MONGODB_DATABASE_NAME: catalogdb
  AWS_REGION: "us-east-1"
  QUEUE_SQS_URL: "https://sqs.us-east-1.amazonaws.com/<ACCOUNT_ID>/payment-processed-catalog"
  REDIS_CONNECTION: "redis:6379"
  OPENSEARCH_URL: "<OPENSEARCH_ENDPOINT>"