apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  RABBITMQ_HOST: "rabbitmq"
  ASPNETCORE_URLS: "http://+:8083"
  ASPNETCORE_ENVIRONMENT: "Development"
  PAYMENT_QUEUE: "catalog-payment-queue"