apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: catalog-api-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: fcg/rabbitmq
        property: username
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: fcg/rabbitmq
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: fcg/jwt
        property: JWT_SECRET
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: fcg/app-aws-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: fcg/app-aws-credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: OPENSEARCH_USERNAME
      remoteRef:
        key: fcg/opensearch
        property: username
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: fcg/opensearch
        property: password
