apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  selector:
    app: catalog-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30003